apiVersion: v1
kind: ConfigMap
metadata:
  name: "demo-frontend-app-config"
  annotations:
    k8s-reload/podDeleteMatch: "app=demo-frontend-app"
data:
  config.cfg: 
    MSG="Welcome to Kubernetes"
---